-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	ui = {
		touch_button_pressed = "rbxassetid://9666952890",
		touch_button_released = "rbxassetid://9667156142",
	},
}