# Tools for foreman to install

[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.0.0" }
tarmac = { github = "Roblox/tarmac", version = "0.7.0" }
remodel = { github = "rojo-rbx/remodel", version = "0.9.1" }